config/routes.rb
Chapter3::Application.routes.draw do
 
 resources :users
 resources :articles
 resources :sessions, only: [:new, :create, :destroy]

 root to: 'static_pages#home'
 
 match '/help', to: 'static_pages#help'
 match '/about', to: 'static_pages#about'
 match '/contact', to: 'static_pages#contact'

 match '/signup',  to: 'users#new'

 match '/signin', to: 'sessions#new'
 match '/signout', to: 'sessions#destroy', via: :delete

match '/km',  to: 'static_pages#km'
match '/java',  to: 'static_pages#java'
match '/rails',  to: 'static_pages#rails'
match '/js',  to: 'static_pages#js'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content, :tag, :title
  validates :user_id, presence: true
  default_scope order: 'articles.created_at DESC'
  paginates_per 50
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  has_many :articles, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  #模板中的只能在视图中显示，如果在这里添加了include的话，也可以在控制层中显示
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
		@user = User.find(current_user)
   		@article = @user.articles.build(params[:article])
	end

	def create
		@user = User.find(current_user)
   		@article = @user.articles.create(params[:article])
   		redirect_to articles_path

	end

	def index
		@user = User.find(current_user)
		@articles = Article.page(params[:page]).per(10)
	end

	def edit
		@user = User.find(current_user)
		@article = @user.articles.find(params[:id])
	end

	def update
		@user = User.find(current_user)		
		@cc=@user.articles.find(params[:id])
		@cc.update_attributes(params[:article])
		redirect_to articles_path
	end 


	def show

		
		@article = Article.find(params[:id])
		@user = User.find(@article.user_id)
		
	end

	def destroy
		@user = User.find(current_user)
		@user.articles.find(params[:id]).destroy
		redirect_to articles_path
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
#encoding: utf-8
class StaticPagesController < ApplicationController
  def home
  	@kms = Article.where("tag = '知识管理'")
    @javas = Article.where("tag = 'java开发'")
    @rails = Article.where("tag = 'rails开发'")
    @jss = Article.where("tag = '脚本语言'")
    @articles = Article.page(params[:page]).per(4)
  end

  def help
  end
  
  def about
  end

  def contact
  end

  def km
    @kms = Article.where("tag = '知识管理'")
  end

  def java
    @javas = Article.where("tag = 'java开发'")
  end

  def rails
    @rails = Article.where("tag = 'rails开发'")
  end

  def js
    @jss = Article.where("tag = '脚本语言'")
  end



	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index,:edit, :update,:destroy]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy



  def show
    @user = User.find(params[:id])
    @articles = @user.articles.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "welcome"
      #下面两句都是可以的
      # redirect_to user_path(@user)
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end


  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      #redirect_to user_path(@user)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end


 



end

app/helpers/application_helper.rb
module ApplicationHelper
# Returns the full title on a per-page basis.
def full_title(page_title)
	base_title = "Ruby on Rails Tutorial Sample App"
	if page_title.empty?
		base_title
	else
	"#{base_title} | #{page_title}"
	end
end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  #调用的是一个方法，若current_user为空
  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.fullpath
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
      image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/articles/edit.html.erb

<div class="row">
    <aside class="span4">
     
      <section>
        用户名：
        <%=@user.name%></br>
        <%=@user.email%>
      </section>
    </aside> 

    <div class="span8">
      <h3 align="center">知识编辑</h3>
      <%= form_for(@article) do |f| %>

      <div class="field">
       <%= f.label :题目 %><br />
        <%= f.text_field :title %>
      </div>

      <div class="field">
       <%= f.label :标签 %><br />
        <%= f.text_field :tag %>
      </div>

      <div class="field">
      <%= f.label :内容 %><br />
      <%= f.kindeditor :content, :width => 670, :height => 400, :langType => 'en' %> 
      </div>

      <div class="actions">
        <%= f.submit  :提交, class: "btn btn-large btn-primary"%>
      </div>
    <% end %>
          
    </div>
</div>



app/views/articles/index.html.erb
<div class="row">
    <aside class="span4">

      <section>
        用户名：
        <%=@user.name%></br>
        <%=@user.email%>
      </section>
    </aside> 

    <div class="span8">
    	<%= link_to '发布知识',new_article_path,class: "btn btn-large btn-primary" %>	
      </br>
      <%=paginate @articles, :theme => 'twitter-bootstrap' %>
    	<ol>
      
      
			<%@articles.each do |t|%>
			<li>
      <%=link_to t.title,t %>   
      <span class="timestamp">
       发表于 <%= time_ago_in_words(t.created_at) %> ago.
      </span>
      </br>
			<%=link_to '编辑',edit_article_path(t) %>|
				<%= link_to '删除',article_path(t), method: :delete, data: { confirm: '确定删除?' } %>
   		</li>
      
       <%end%>
      </ol>   
    </div>
</div>


app/views/articles/new.html.erb


<div class="row">
    <aside class="span4">    
      <section>
        用户名：
        <%=@user.name%></br>
        <%=@user.email%>
      </section>
    </aside> 


<div class="span8">
<%= form_for(@article) do |f| %>

  <div class="field">
    <%= f.label :题目 %><br />
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :标签 %><br />
    <%= f.text_field :tag%>


  </div>
    
  <div class="field">
    <%= f.label :内容 %><br />
    <%= f.kindeditor :content, :width => 670, :height => 400, :langType => 'en' %> 
  </div>
  
  <div class="actions">
    <%= f.submit  :提交 , class: "btn btn-large btn-primary" %>
  </div>
<% end %>
</div>
  
</div>


app/views/articles/show.html.erb
<div class="row">  
    <div class="span12">
    	<%= link_to '返回文章列表',root_path%></br>
    	   主题:<%=@article.title%>
			</br>
			主题:<%=@article.tag%>
			</br>
		   内容
		    </br>
		   <%=raw @article.content%>
			</br>					
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<nav>
		<ul>
			<li><small><%= link_to "关于本站", about_path %></small></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "迈向产品经理", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">       
          <% if signed_in? %>
            <li><%= link_to "用户群", users_path %></li>
            <li><%= link_to "发布知识", articles_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                账户 <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "资料显示", current_user %></li>
                <li><%= link_to "设置更新", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "退出", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
                
                <li><%= link_to "关于作者", about_url%></li>
                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
               <!--  <li><a href="http://localhost:3000/about">关于作者&nbsp;&nbsp;&nbsp;</a></li> -->
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>



<title><%="迈向产品经理" %></title>
<%= stylesheet_link_tag "application", media: "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<%= render 'layouts/shim' %>
</head>
	<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
	        <div class="alert alert-<%= key %>"><%= value %></div>
	    <% end %>

	<%= yield %>
    <%= render 'layouts/footer' %>
	</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li># <%= msg %></li>
    <% end %>
    </ul>
  </div> 
<% end %>

app/views/static_pages/about.html.erb
这是程序猿作品

app/views/static_pages/contact.html.erb
联系我们</br>
我们都是程序猿

app/views/static_pages/home.html.erb
 <div class="row">
        <div class="span10">

         <section>
           <h3><small>关注互联网、个人自我管理</small></h3>
           
           <hr>
        </section>

        <section>
        <%=paginate @articles, :theme => 'twitter-bootstrap' %>
          
          <ul>
			<%@articles.each do |article|%>
				<li><%=link_to article.title,article_path(article)%></br>
					<%=raw article.content%>
				</li>
			<%end%>
		  </ul>
		<section>
        </div>



        <div class="span2">


	      <section align="left">  
	      	    &nbsp;&nbsp;&nbsp;<img src="assets/zhengjiajun.jpg">
	      	   
	      	

	      </section>

	      <section>
	         
	         	 &nbsp;&nbsp;<i class="icon-chevron-right"></i>热爱互联网</br>
	         	 &nbsp;&nbsp;<i class="icon-chevron-right"></i>浙江大学</br>
	         	 &nbsp;&nbsp;<i class="icon-chevron-right"></i><a href="www.huyou.biz">常山胡柚</a>
	         
	      </section>

	      <section>   
          
	      </br>
	      </br>
	      </br>
	      </br>
	      </br>
	      </br>

          <ul>
           
			<li><%=link_to '知识管理',km_path%>(<%=@kms.count%>)</li>
			<li><%=link_to 'rails开发',rails_path%>(<%=@rails.count%>)</li>
			<li><%=link_to 'java学习',java_path%>(<%=@javas.count%>)</li>
			<li><%=link_to '脚本学习',js_path%>(<%=@jss.count%>)</li>
		  </ul>

		  </section>

        </div>      
</div>

app/views/static_pages/java.html.erb
<ul>
<%@javas.each do |java|%>
	<li><%=link_to java.title,article_path(java)%></br>
		<%=java.content%></li>
<%end%>
</ul>

app/views/static_pages/js.html.erb
<ul>
<%@jss.each do |js|%>
	<li><%=link_to js.title,article_path(js)%></br>
		<%=js.content%></li>
<%end%>
</ul>

app/views/static_pages/km.html.erb
<ul>
<%@kms.each do |km|%>
	<li><%=link_to km.title,article_path(km)%></br>
		<%=raw km.content%></li>
<%end%>
</ul>




app/views/static_pages/rails.html.erb
<ul>
<%@rails.each do |rail|%>
	<li><%=link_to rail.title,article_path(rail)%></br>
		<%=raw rail.content%></li>
<%end%>
</ul>

app/views/static_pages/ruby.html.erb
<ul>
<%@rails.each do |rail|%>
	<li><%=link_to rail.title,article_path(rail)%></br>
		<%=raw rail.content%></li>
<%end%>
</ul>

app/views/users/_user.html.erb
<li>
	<%= link_to user.name, user %>

	<% if current_user.admin? && !current_user?(user) %>
	| <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" }%>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h3 align="center">更新资料</h3>

<div class="row">
  <div class="span6 offset3">
  <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h3 align="center">所有的用户</h3>

<ul class="users">
	<ul class="users">
		<%= render @users %>
	</ul>
</ul>


app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="row">
  <div class="span4">
    <%= form_for(@user) do |f| %>   
      <%= render 'shared/error_messages' %>
      <h3 align="center">注册</h3>
      <%= f.label :名字 %>
      <%= f.text_field :name %>

      <%= f.label :邮件 %>
      <%= f.text_field :email %>

      <%= f.label :密码 %>
      <%= f.password_field :password %>

      <%= f.label :密码确认%>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "注册", class: "btn btn-large btn-primary" %>
      <p><%= link_to "返回登录" , signin_path %></p>

    <% end %>
  </div>

  <div class="span8">
    <div class="hero-unit">   
   
    <h3 align="center">遇到未来的自己</h3>
    <img src="assets/relation.png" alt="这是一张图片"/>


    </div>
  </div>

</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				
				<%= @user.name %>
			</h1>
		</section>
	</aside>
	
	<aside class="span8">
		<section>
				<ul>
				<%@articles.each do |article| %>
					<li><%=link_to article.title,article_path(article) %></li>
				<%end%>
			    </ul>
		</section>
	</aside>
</div>
